services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend/mindfusion
    container_name: backend
    command: uvicorn run:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
    volumes:
      - ./backend/mindfusion:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend/mindfusion
    container_name: frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./frontend/mindfusion:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

volumes:
  postgres_data: