from app.services.interfaces.review_service_interface import ReviewServiceInterface
from app.services.interfaces.session_service_interface import SessionServiceInterface
from app.services.interfaces.tutor_service_interface import TutorServiceInterface
from app.services.interfaces.user_service_interface import UserServiceInterface

from abc import ABC, abstractmethod
from typing import List